### PR TITLE
Rename duplicates

### PR DESCRIPTION
**Pull request by ThorpeJosh**

### CODE REVIEW

**Comment by changukshin** [comment]
Failed on unit tests.
Could you advise regarding to the results of the Unit Tests? @ThorpeJosh

**Comment by ThorpeJosh** [comment]
> Failed on unit tests. Could you advise regarding to the results of the Unit Tests? @ThorpeJosh

Hi @changukshin , I have added to the readme on how to run the unit-tests locally. The tests that check the sorting algorithm seem to be failing (indicating the algorithm is not behaving the same anymore), this isn't surprising as you have changed the algorithm. I suggest trying ```pytest``` on your machine as it will be faster to get results. Likely a new unit tests will need adding and some others might need tweaking if the algorithm behaves differently now.

**Comment by changukshin** [comment]
The test was failed because the code parsing date from filename/exif sometimes raise exception.
And I didn't process the try-catch properly. I moved try-catch block to catch exceptions.
Review required. Regards,

**Comment by changukshin** [comment]
All settled and All passed.
Need review. @ThorpeJosh

**Comment by ThorpeJosh** [comment]
Thanks @changukshin. It looks like it will need rebasing onto main (my badge commit will need dropping). If you can clean up commits (squash and rename) a bit too that will make it easier to review. Cheers

**Comment by ThorpeJosh** [comment]
@changukshin, could you please do me a favour and update the Readme image with a screenshot of the new UI?
MacOS dark theme would be great.

**Comment by changukshin** [comment]
I'm on it. @ThorpeJosh

**Comment by changukshin** [comment]
All done. 
- Commits:
    - squashed some commits.
    - commits from [87b92b1](https://github.com/ThorpeJosh/image-sorting-tool/pull/19/commits/87b92b108b0469aa22c74bdaf83ba820d5613b6d) to [48cbae5](https://github.com/ThorpeJosh/image-sorting-tool/pull/19/commits/48cbae5a85ff542129fcee478d23d0615e18236f) is unmodified and left as itself.
 - Image:
     - updated.

**Comment by changukshin** [comment]
Looks good to me.
Need review. @ThorpeJosh

**Comment by changukshin** [comment]
- Logic changed : Now the name conflict check process is processed during the 'file collection' stage.
- data structure changed : result of 'file collection' stage.
- minor modification of logging and testing

**Comment by changukshin** [comment]
Need review.
@ThorpeJosh

**Comment by changukshin** [comment]
All settled.
Need review.
@ThorpeJosh

**Pull request merged**
